[site]
bucket = "."

[build]
command = ""

[pages]
pages_build_output_dir = "."

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 